import "./style.css";

import { fetchSceneAndMount_torus_knot } from "./polygonjs/scenes/torus_knot/autogenerated/fetchSceneAndMount";
// import { fetchSceneAndMount_scene_01 } from "./polygonjs/scenes/scene_01/autogenerated/fetchSceneAndMount";
//
// fetchSceneAndMount_scene_01({
//     domElement: "scene_01",
// });

// this one has actor1.txt in root/geo1  the javascript function
fetchSceneAndMount_torus_knot({
    domElement: "scene_02",
});
